run-shell "powerline-daemon -q"
set -g default-terminal "screen-256color"
source "/home/piero/.local/lib/python2.7/site-packages/powerline_status-2.3.dev9999+git.38ce0e73c8a21793d147581ba8932252154e7e3b-py2.7.egg/powerline/bindings/tmux/powerline.conf"
